name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.14.0]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build

FTP-Deploy-Action:
  name: FTP-Deploy-Action
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2.1.0
    with:
      fetch-depth: 2
  - name: FTP-Deploy-Action
  uses: SamKirkland/FTP-Deploy-Action@3.1.1
  with:
    ftp-server: ftp://ftp.funtiontales.domains.swarthmore.edu:21/public_html
    ftp-username: admin
    ftp-password: ${{ secrets.FTP_PASSWORD }}