name: Publish Website
on: 
  push
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
    uses: SamKirkland/FTP-Deploy-Action@3.1.1
    with:
      ftp-server: ftp://ftp.funtiontales.domains.swarthmore.edu:21/public_html
      ftp-username: admin
      ftp-password: ${{ secrets.FTP_PASSWORD }}